export const ImageIcons = {
    OnboardingScreen: require('@/assets/images/onboarding.png'),
    Logo: require('@/assets/images/logo.png'),
    BackgroundImage: require('@/assets/images/background.png'),
    HomeScreen: require('@/assets/images/homeScreen.png'),
    FollowUp: require('@/assets/images/home/followUp.png'),
    FollowUp2: require('@/assets/images/home/followUp2.png'),
    GirlImage: require('@/assets/images/home/girl.png'),
    Calendar: require('@/assets/images/home/calendar.png'),
    Calendar2: require('@/assets/images/home/calendar2.png'),
    GirlImage2: require('@/assets/images/home/girl2.png'),
    GirlImage3: require('@/assets/images/home/girl3.png'),
    GirlImage4: require('@/assets/images/home/girl4.png'),
    WomanImage: require('@/assets/images/home/women.png'),
    BoyImage: require('@/assets/images/home/boy.png'),
    BoyImage2: require('@/assets/images/home/boy2.png'),
    BoyImage3: require('@/assets/images/home/boy3.png'),
    MenImage: require('@/assets/images/home/men.png'),
    NetworkingPlaybook: require('@/assets/images/home/networking-playbook.png'),
    Follow_up: require('@/assets/images/home/follow-up.png'),
    CraftMessage: require('@/assets/images/home/craft-your-message.png'),
    ConnectCalendar: require('@/assets/images/home/connect-calendar.png'),
    ThankYou: require('@/assets/images/home/thank-you.png'),
    Assistant: require('@/assets/images/assistant.png'),
}